package me.jinkun.opennews.features.news.bean;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "NEWS_READ".
 */
public class NewsRead implements java.io.Serializable {

    private Long id;
     /*详情ID*/
    private String docid;
     /*是否已读0未读，1已读*/
    private Integer isRead;

    // KEEP FIELDS - put your custom fields here
    public final static int READ_NO = 0;
    public final static int READ_YES = 1;
    // KEEP FIELDS END

    public NewsRead() {
    }

    public NewsRead(Long id) {
        this.id = id;
    }

    public NewsRead(Long id, String docid, Integer isRead) {
        this.id = id;
        this.docid = docid;
        this.isRead = isRead;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDocid() {
        return docid;
    }

    public void setDocid(String docid) {
        this.docid = docid;
    }

    public Integer getIsRead() {
        return isRead;
    }

    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
