package me.jinkun.opennews.data.domain;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "NEWS_CHANNEL".
 */
public class NewsChannel implements java.io.Serializable {

    private Long id;
     /*暂不知道有什么用*/
    private String topicid;
     /*频道的名字*/
    private String tname;
     /*文章的ID*/
    private String tid;
     /*已选的频道0-->已选择的，1-->未选择的*/
    private Integer isSelected;
     /*排序*/
    private Integer orderNum;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public NewsChannel() {
    }

    public NewsChannel(Long id) {
        this.id = id;
    }

    public NewsChannel(Long id, String topicid, String tname, String tid, Integer isSelected, Integer orderNum) {
        this.id = id;
        this.topicid = topicid;
        this.tname = tname;
        this.tid = tid;
        this.isSelected = isSelected;
        this.orderNum = orderNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTopicid() {
        return topicid;
    }

    public void setTopicid(String topicid) {
        this.topicid = topicid;
    }

    public String getTname() {
        return tname;
    }

    public void setTname(String tname) {
        this.tname = tname;
    }

    public String getTid() {
        return tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public Integer getIsSelected() {
        return isSelected;
    }

    public void setIsSelected(Integer isSelected) {
        this.isSelected = isSelected;
    }

    public Integer getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
